
let books = [
{
    "id": 1,
    "titulo": "Ingeniería de Software",
    "autor": "Roger S. Pressman",
    "isbn": "978-970-10-6615-4",
    "editorial": "McGraw-Hill",
    "anioPublicacion": 2010,
    "categoria": "Ingeniería",
    "numeroPaginas": 872,
    "disponible": true,
    "ubicacion": "Estante A-01",
    "descripcion": "Texto guía fundamental para principios de arquitectura y procesos de software.",
    "fechaRegistro": "2026-01-15T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 2,
    "titulo": "Clean Code: A Handbook of Agile Software Craftsmanship",
    "autor": "Robert C. Martin",
    "isbn": "978-0-13-235088-4",
    "editorial": "Prentice Hall",
    "anioPublicacion": 2008,
    "categoria": "Programación",
    "numeroPaginas": 464,
    "disponible": false,
    "ubicacion": "Estante B-15",
    "descripcion": "Manual de buenas prácticas de programación, refactorización y código limpio.",
    "fechaRegistro": "2026-02-10T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 3,
    "titulo": "El principito",
    "autor": "Antoine de Saint-Exupéry",
    "isbn": "978-958-04-9999-9",
    "editorial": "Norma",
    "anioPublicacion": 2015,
    "categoria": "Literatura",
    "numeroPaginas": 96,
    "disponible": true,
    "ubicacion": "Estante C-03",
    "descripcion": "Obra literaria clásica universal.",
    "fechaRegistro": "2026-03-01T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 4,
    "titulo": "Design Patterns: Elements of Reusable Object-Oriented Software",
    "autor": "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    "isbn": "978-0-201-63361-0",
    "editorial": "Addison-Wesley",
    "anioPublicacion": 1994,
    "categoria": "Programación",
    "numeroPaginas": 395,
    "disponible": true,
    "ubicacion": "Estante B-01",
    "descripcion": "Catálogo fundamental de patrones de diseño orientados a objetos.",
    "fechaRegistro": "2026-03-02T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 5,
    "titulo": "Refactoring: Improving the Design of Existing Code",
    "autor": "Martin Fowler",
    "isbn": "978-0-13-475759-9",
    "editorial": "Addison-Wesley",
    "anioPublicacion": 2018,
    "categoria": "Programación",
    "numeroPaginas": 448,
    "disponible": true,
    "ubicacion": "Estante B-02",
    "descripcion": "Guía práctica para refactorizar y mejorar la estructura interna del código.",
    "fechaRegistro": "2026-03-02T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 6,
    "titulo": "The Pragmatic Programmer",
    "autor": "Andrew Hunt, David Thomas",
    "isbn": "978-0-13-595705-9",
    "editorial": "Addison-Wesley",
    "anioPublicacion": 2019,
    "categoria": "Programación",
    "numeroPaginas": 352,
    "disponible": false,
    "ubicacion": "Estante B-03",
    "descripcion": "Consejos y enfoques prácticos para el desarrollo profesional de software.",
    "fechaRegistro": "2026-03-02T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 7,
    "titulo": "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    "autor": "Eric Evans",
    "isbn": "978-0-321-12521-7",
    "editorial": "Addison-Wesley",
    "anioPublicacion": 2003,
    "categoria": "Arquitectura de Software",
    "numeroPaginas": 560,
    "disponible": true,
    "ubicacion": "Estante A-02",
    "descripcion": "Introducción y principios del diseño guiado por el dominio (DDD).",
    "fechaRegistro": "2026-03-03T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 8,
    "titulo": "Clean Architecture: A Craftsman's Guide to Software Structure and Design",
    "autor": "Robert C. Martin",
    "isbn": "978-0-13-449416-6",
    "editorial": "Prentice Hall",
    "anioPublicacion": 2017,
    "categoria": "Arquitectura de Software",
    "numeroPaginas": 432,
    "disponible": true,
    "ubicacion": "Estante A-03",
    "descripcion": "Principios de arquitectura limpia y desacoplamiento de componentes.",
    "fechaRegistro": "2026-03-03T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 9,
    "titulo": "Introduction to Algorithms",
    "autor": "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    "isbn": "978-0-262-03384-8",
    "editorial": "MIT Press",
    "anioPublicacion": 2009,
    "categoria": "Ciencias de la Computación",
    "numeroPaginas": 1312,
    "disponible": true,
    "ubicacion": "Estante A-04",
    "descripcion": "Texto exhaustivo sobre diseño y análisis de algoritmos computacionales.",
    "fechaRegistro": "2026-03-04T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 10,
    "titulo": "Sistemas Operativos Conceptos Fundamentales",
    "autor": "Abraham Silberschatz, Peter B. Galvin, Greg Gagne",
    "isbn": "978-607-15-0772-2",
    "editorial": "McGraw-Hill",
    "anioPublicacion": 2014,
    "categoria": "Sistemas Operativos",
    "numeroPaginas": 840,
    "disponible": false,
    "ubicacion": "Estante D-01",
    "descripcion": "Conceptos clave sobre procesos, memoria, almacenamiento y concurrencia.",
    "fechaRegistro": "2026-03-04T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 11,
    "titulo": "Redes de Computadoras",
    "autor": "Andrew S. Tanenbaum, David J. Wetherall",
    "isbn": "978-607-32-0823-9",
    "editorial": "Pearson",
    "anioPublicacion": 2012,
    "categoria": "Redes",
    "numeroPaginas": 960,
    "disponible": true,
    "ubicacion": "Estante D-02",
    "descripcion": "Estudio detallado de la arquitectura de redes y del modelo OSI e TCP/IP.",
    "fechaRegistro": "2026-03-05T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 12,
    "titulo": "Fundamentos de Bases de Datos",
    "autor": "Silberschatz, Korth, Sudarshan",
    "isbn": "978-84-481-9033-0",
    "editorial": "McGraw-Hill",
    "anioPublicacion": 2014,
    "categoria": "Bases de Datos",
    "numeroPaginas": 800,
    "disponible": true,
    "ubicacion": "Estante D-03",
    "descripcion": "Principios del modelo relacional, SQL y optimización de consultas.",
    "fechaRegistro": "2026-03-05T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 13,
    "titulo": "Designing Data-Intensive Applications",
    "autor": "Martin Kleppmann",
    "isbn": "978-1-4919-0307-0",
    "editorial": "O'Reilly Media",
    "anioPublicacion": 2017,
    "categoria": "Bases de Datos",
    "numeroPaginas": 616,
    "disponible": true,
    "ubicacion": "Estante D-04",
    "descripcion": "Principios clave para el diseño de sistemas distribuidos y escalables.",
    "fechaRegistro": "2026-03-06T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 14,
    "titulo": "Learning Python",
    "autor": "Mark Lutz",
    "isbn": "978-1-4493-5573-9",
    "editorial": "O'Reilly Media",
    "anioPublicacion": 2013,
    "categoria": "Programación",
    "numeroPaginas": 1600,
    "disponible": false,
    "ubicacion": "Estante B-04",
    "descripcion": "Guía completa para dominar el lenguaje de programación Python.",
    "fechaRegistro": "2026-03-06T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 15,
    "titulo": "Python Crash Course",
    "autor": "Eric Matthes",
    "isbn": "978-1-59327-928-8",
    "editorial": "No Starch Press",
    "anioPublicacion": 2019,
    "categoria": "Programación",
    "numeroPaginas": 544,
    "disponible": true,
    "ubicacion": "Estante B-05",
    "descripcion": "Introducción práctica a Python orientada a proyectos reales.",
    "fechaRegistro": "2026-03-07T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 16,
    "titulo": "Eloquent JavaScript",
    "autor": "Marijn Haverbeke",
    "isbn": "978-1-59327-950-9",
    "editorial": "No Starch Press",
    "anioPublicacion": 2018,
    "categoria": "Programación",
    "numeroPaginas": 472,
    "disponible": true,
    "ubicacion": "Estante B-06",
    "descripcion": "Guía moderna sobre JavaScript, programación funcional y asincronía.",
    "fechaRegistro": "2026-03-07T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 17,
    "titulo": "You Don't Know JS Yet: Scope & Closures",
    "autor": "Kyle Simpson",
    "isbn": "979-8601673838",
    "editorial": "Independently Published",
    "anioPublicacion": 2020,
    "categoria": "Programación",
    "numeroPaginas": 282,
    "disponible": true,
    "ubicacion": "Estante B-07",
    "descripcion": "Análisis profundo sobre el ámbito, hoisting y cierres en JavaScript.",
    "fechaRegistro": "2026-03-08T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 18,
    "titulo": "Java: The Complete Reference",
    "autor": "Herbert Schildt",
    "isbn": "978-1-260-44023-2",
    "editorial": "McGraw-Hill",
    "anioPublicacion": 2018,
    "categoria": "Programación",
    "numeroPaginas": 1248,
    "disponible": false,
    "ubicacion": "Estante B-08",
    "descripcion": "Referencia exhaustiva del lenguaje Java, la JVM y sus librerías estándar.",
    "fechaRegistro": "2026-03-08T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 19,
    "titulo": "Effective Java",
    "autor": "Joshua Bloch",
    "isbn": "978-0-13-468599-1",
    "editorial": "Addison-Wesley",
    "anioPublicacion": 2017,
    "categoria": "Programación",
    "numeroPaginas": 416,
    "disponible": true,
    "ubicacion": "Estante B-09",
    "descripcion": "Mejores prácticas para escribir código idiomático y robusto en Java.",
    "fechaRegistro": "2026-03-09T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 20,
    "titulo": "C++ Primer",
    "autor": "Stanley B. Lippman, Josée Lajoie, Barbara E. Moo",
    "isbn": "978-0-321-71411-4",
    "editorial": "Addison-Wesley",
    "anioPublicacion": 2012,
    "categoria": "Programación",
    "numeroPaginas": 1080,
    "disponible": true,
    "ubicacion": "Estante B-10",
    "descripcion": "Manual completo para el aprendizaje de C++ moderno.",
    "fechaRegistro": "2026-03-09T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 21,
    "titulo": "Artificial Intelligence: A Modern Approach",
    "autor": "Stuart Russell, Peter Norvig",
    "isbn": "978-0-13-461099-3",
    "editorial": "Pearson",
    "anioPublicacion": 2020,
    "categoria": "Inteligencia Artificial",
    "numeroPaginas": 1152,
    "disponible": true,
    "ubicacion": "Estante E-01",
    "descripcion": "El texto universitario de referencia para inteligencia artificial.",
    "fechaRegistro": "2026-03-10T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 22,
    "titulo": "Deep Learning",
    "autor": "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
    "isbn": "978-0-262-03561-3",
    "editorial": "MIT Press",
    "anioPublicacion": 2016,
    "categoria": "Inteligencia Artificial",
    "numeroPaginas": 800,
    "disponible": false,
    "ubicacion": "Estante E-02",
    "descripcion": "Fundamentos matemáticos y prácticos de redes neuronales profundas.",
    "fechaRegistro": "2026-03-10T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 23,
    "titulo": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
    "autor": "Aurélien Géron",
    "isbn": "978-1-4920-3264-9",
    "editorial": "O'Reilly Media",
    "anioPublicacion": 2019,
    "categoria": "Inteligencia Artificial",
    "numeroPaginas": 850,
    "disponible": true,
    "ubicacion": "Estante E-03",
    "descripcion": "Guía práctica para construir sistemas de aprendizaje automático con Python.",
    "fechaRegistro": "2026-03-11T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 24,
    "titulo": "Compiladores: Principios, Técnicas y Herramientas",
    "autor": "Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman",
    "isbn": "978-0-321-48681-3",
    "editorial": "Pearson",
    "anioPublicacion": 2008,
    "categoria": "Ciencias de la Computación",
    "numeroPaginas": 1000,
    "disponible": true,
    "ubicacion": "Estante A-05",
    "descripcion": "Conocido como el libro del dragón, referente en teoría de compiladores.",
    "fechaRegistro": "2026-03-11T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 25,
    "titulo": "Ciberseguridad: Fundamentos de la Seguridad Informática",
    "autor": "Álvaro Gómez Vieites",
    "isbn": "978-84-267-2856-2",
    "editorial": "Marcombo",
    "anioPublicacion": 2021,
    "categoria": "Ciberseguridad",
    "numeroPaginas": 320,
    "disponible": true,
    "ubicacion": "Estante F-01",
    "descripcion": "Conceptos clave para defender sistemas informáticos e infraestructuras.",
    "fechaRegistro": "2026-03-12T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 26,
    "titulo": "The Web Application Hacker's Handbook",
    "autor": "Dafydd Stuttard, Marcus Pinto",
    "isbn": "978-1-118-02647-2",
    "editorial": "Wiley",
    "anioPublicacion": 2011,
    "categoria": "Ciberseguridad",
    "numeroPaginas": 912,
    "disponible": false,
    "ubicacion": "Estante F-02",
    "descripcion": "Descubrimiento y prevención de vulnerabilidades de seguridad web.",
    "fechaRegistro": "2026-03-12T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 27,
    "titulo": "Kali Linux Revealed",
    "autor": "Raphaël Hertzog, Jim O'Gorman",
    "isbn": "978-0-9964525-4-1",
    "editorial": "Offensive Security Press",
    "anioPublicacion": 2017,
    "categoria": "Ciberseguridad",
    "numeroPaginas": 344,
    "disponible": true,
    "ubicacion": "Estante F-03",
    "descripcion": "Guía oficial de administración y pruebas de penetración con Kali Linux.",
    "fechaRegistro": "2026-03-13T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 28,
    "titulo": "The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win",
    "autor": "Gene Kim, Kevin Behr, George Spafford",
    "isbn": "978-1942788294",
    "editorial": "IT Revolution Press",
    "anioPublicacion": 2018,
    "categoria": "DevOps",
    "numeroPaginas": 432,
    "disponible": true,
    "ubicacion": "Estante G-01",
    "descripcion": "Novela sobre transformación digital, integración continua y cultura DevOps.",
    "fechaRegistro": "2026-03-13T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 29,
    "titulo": "The DevOps Handbook",
    "autor": "Gene Kim, Jez Humble, Patrick Debois, John Willis",
    "isbn": "978-1942788003",
    "editorial": "IT Revolution Press",
    "anioPublicacion": 2016,
    "categoria": "DevOps",
    "numeroPaginas": 480,
    "disponible": true,
    "ubicacion": "Estante G-02",
    "descripcion": "Guía técnica para automatización, despliegue continuo y estabilidad operacional.",
    "fechaRegistro": "2026-03-14T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 30,
    "titulo": "Docker Deep Dive",
    "autor": "Nigel Poulton",
    "isbn": "978-1916585256",
    "editorial": "Independently Published",
    "anioPublicacion": 2020,
    "categoria": "DevOps",
    "numeroPaginas": 310,
    "disponible": false,
    "ubicacion": "Estante G-03",
    "descripcion": "Manual exhaustivo para la contenedorización de aplicaciones con Docker.",
    "fechaRegistro": "2026-03-14T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 31,
    "titulo": "Kubernetes Up & Running",
    "autor": "Brendan Burns, Joe Beda, Kelsey Hightower",
    "isbn": "978-1492046530",
    "editorial": "O'Reilly Media",
    "anioPublicacion": 2019,
    "categoria": "DevOps",
    "numeroPaginas": 278,
    "disponible": true,
    "ubicacion": "Estante G-04",
    "descripcion": "Fundamentos para la orquestación de contenedores a escala con Kubernetes.",
    "fechaRegistro": "2026-03-15T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 32,
    "titulo": "Building Microservices",
    "autor": "Sam Newman",
    "isbn": "978-1492034025",
    "editorial": "O'Reilly Media",
    "anioPublicacion": 2021,
    "categoria": "Arquitectura de Software",
    "numeroPaginas": 612,
    "disponible": true,
    "ubicacion": "Estante A-06",
    "descripcion": "Diseño, modelado y despliegue de arquitecturas basadas en microservicios.",
    "fechaRegistro": "2026-03-15T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 33,
    "titulo": "Site Reliability Engineering",
    "autor": "Betsy Beyer, Chris Jones, Jennifer Petoff, Niall Richard Murphy",
    "isbn": "978-1491929124",
    "editorial": "O'Reilly Media",
    "anioPublicacion": 2016,
    "categoria": "Sistemas",
    "numeroPaginas": 550,
    "disponible": true,
    "ubicacion": "Estante G-05",
    "descripcion": "Cómo Google gestiona sus sistemas de producción a gran escala.",
    "fechaRegistro": "2026-03-16T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 34,
    "titulo": "Cien años de soledad",
    "autor": "Gabriel García Márquez",
    "isbn": "978-0307474728",
    "editorial": "RAE / Alfaguara",
    "anioPublicacion": 1967,
    "categoria": "Literatura",
    "numeroPaginas": 496,
    "disponible": true,
    "ubicacion": "Estante C-01",
    "descripcion": "Obra cumbre del realismo mágico y de la literatura hispanoamericana.",
    "fechaRegistro": "2026-03-16T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 35,
    "titulo": "El amor en los tiempos del cólera",
    "autor": "Gabriel García Márquez",
    "isbn": "978-0307387264",
    "editorial": "Debolsillo",
    "anioPublicacion": 1985,
    "categoria": "Literatura",
    "numeroPaginas": 368,
    "disponible": false,
    "ubicacion": "Estante C-02",
    "descripcion": "Historia de amor perdurable ambientada en el Caribe colombiano.",
    "fechaRegistro": "2026-03-17T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 36,
    "titulo": "Don Quijote de la Mancha",
    "autor": "Miguel de Cervantes",
    "isbn": "978-8420412146",
    "editorial": "Alfaguara",
    "anioPublicacion": 1605,
    "categoria": "Literatura",
    "numeroPaginas": 1080,
    "disponible": true,
    "ubicacion": "Estante C-04",
    "descripcion": "Obra cumbre de la literatura en lengua castellana.",
    "fechaRegistro": "2026-03-17T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 37,
    "titulo": "Pedro Páramo",
    "autor": "Juan Rulfo",
    "isbn": "978-8437604183",
    "editorial": "Cátedra",
    "anioPublicacion": 1955,
    "categoria": "Literatura",
    "numeroPaginas": 136,
    "disponible": true,
    "ubicacion": "Estante C-05",
    "descripcion": "Obra maestra de la narrativa mexicana del siglo XX.",
    "fechaRegistro": "2026-03-18T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 38,
    "titulo": "Ficciones",
    "autor": "Jorge Luis Borges",
    "isbn": "978-8497598835",
    "editorial": "Debolsillo",
    "anioPublicacion": 1944,
    "categoria": "Literatura",
    "numeroPaginas": 224,
    "disponible": true,
    "ubicacion": "Estante C-06",
    "descripcion": "Colección de cuentos emblemáticos del laberinto borgesiano.",
    "fechaRegistro": "2026-03-18T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 39,
    "titulo": "Rayuela",
    "autor": "Julio Cortázar",
    "isbn": "978-8437604572",
    "editorial": "Cátedra",
    "anioPublicacion": 1963,
    "categoria": "Literatura",
    "numeroPaginas": 600,
    "disponible": false,
    "ubicacion": "Estante C-07",
    "descripcion": "Novela de la contranovela con múltiples posibilidades de lectura.",
    "fechaRegistro": "2026-03-19T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 40,
    "titulo": "La ciudad y los perros",
    "autor": "Mario Vargas Llosa",
    "isbn": "978-8420471839",
    "editorial": "Alfaguara",
    "anioPublicacion": 1963,
    "categoria": "Literatura",
    "numeroPaginas": 448,
    "disponible": true,
    "ubicacion": "Estante C-08",
    "descripcion": "Novela ambientada en el Colegio Militar Leoncio Prado de Lima.",
    "fechaRegistro": "2026-03-19T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 41,
    "titulo": "Ensayo sobre la ceguera",
    "autor": "José Saramago",
    "isbn": "978-8420404325",
    "editorial": "Alfaguara",
    "anioPublicacion": 1995,
    "categoria": "Literatura",
    "numeroPaginas": 384,
    "disponible": true,
    "ubicacion": "Estante C-09",
    "descripcion": "Metáfora desgarradora sobre los límites de la condición humana.",
    "fechaRegistro": "2026-03-20T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 42,
    "titulo": "1984",
    "autor": "George Orwell",
    "isbn": "978-8499890944",
    "editorial": "Debolsillo",
    "anioPublicacion": 1949,
    "categoria": "Ficción Dystópica",
    "numeroPaginas": 352,
    "disponible": true,
    "ubicacion": "Estante C-10",
    "descripcion": "Visión distópica del totalitarismo y el control social.",
    "fechaRegistro": "2026-03-20T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 43,
    "titulo": "Un mundo feliz",
    "autor": "Aldous Huxley",
    "isbn": "978-8497594257",
    "editorial": "Debolsillo",
    "anioPublicacion": 1932,
    "categoria": "Ficción Dystópica",
    "numeroPaginas": 256,
    "disponible": false,
    "ubicacion": "Estante C-11",
    "descripcion": "Sociedad futurista condicionada para el consumo y la estabilidad.",
    "fechaRegistro": "2026-03-21T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 44,
    "titulo": "Fahrenheit 451",
    "autor": "Ray Bradbury",
    "isbn": "978-8445074251",
    "editorial": "Minotauro",
    "anioPublicacion": 1953,
    "categoria": "Ficción Dystópica",
    "numeroPaginas": 192,
    "disponible": true,
    "ubicacion": "Estante C-12",
    "descripcion": "Un futuro donde los libros están prohibidos y los bomberos los queman.",
    "fechaRegistro": "2026-03-21T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 45,
    "titulo": "Dune",
    "autor": "Frank Herbert",
    "isbn": "978-8445074732",
    "editorial": "Minotauro",
    "anioPublicacion": 1965,
    "categoria": "Ciencia Ficción",
    "numeroPaginas": 784,
    "disponible": true,
    "ubicacion": "Estante C-13",
    "descripcion": "Épica de ciencia ficción ambientada en el planeta desértico Arrakis.",
    "fechaRegistro": "2026-03-22T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 46,
    "titulo": "Fundación",
    "autor": "Isaac Asimov",
    "isbn": "978-8497599245",
    "editorial": "Debolsillo",
    "anioPublicacion": 1951,
    "categoria": "Ciencia Ficción",
    "numeroPaginas": 256,
    "disponible": true,
    "ubicacion": "Estante C-14",
    "descripcion": "Primer volumen de la saga galáctica de la psicohistoria de Hari Seldon.",
    "fechaRegistro": "2026-03-22T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 47,
    "titulo": "Neuromante",
    "autor": "William Gibson",
    "isbn": "978-8445076040",
    "editorial": "Minotauro",
    "anioPublicacion": 1984,
    "categoria": "Ciencia Ficción",
    "numeroPaginas": 320,
    "disponible": false,
    "ubicacion": "Estante C-15",
    "descripcion": "Novela pionera del género cyberpunk y del concepto del ciberespacio.",
    "fechaRegistro": "2026-03-23T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 48,
    "titulo": "Crítica de la razón pura",
    "autor": "Immanuel Kant",
    "isbn": "978-8424936235",
    "editorial": "Gredos",
    "anioPublicacion": 1781,
    "categoria": "Filosofía",
    "numeroPaginas": 700,
    "disponible": true,
    "ubicacion": "Estante H-01",
    "descripcion": "Indagación sobre los límites y posibilidades del conocimiento humano.",
    "fechaRegistro": "2026-03-23T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 49,
    "titulo": "Así habló Zaratustra",
    "autor": "Friedrich Nietzsche",
    "isbn": "978-8420664287",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1883,
    "categoria": "Filosofía",
    "numeroPaginas": 496,
    "disponible": true,
    "ubicacion": "Estante H-02",
    "descripcion": "Obra poético-filosófica que expone la idea del superhombre.",
    "fechaRegistro": "2026-03-24T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 50,
    "titulo": "El ser y el tiempo",
    "autor": "Martin Heidegger",
    "isbn": "978-8437615028",
    "editorial": "Trotta",
    "anioPublicacion": 1927,
    "categoria": "Filosofía",
    "numeroPaginas": 480,
    "disponible": true,
    "ubicacion": "Estante H-03",
    "descripcion": "Análisis ontológico sobre la existencia humana y la naturaleza del ser.",
    "fechaRegistro": "2026-03-24T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 51,
    "titulo": "Sapiens: De animales a dioses",
    "autor": "Yuval Noah Harari",
    "isbn": "978-8499926223",
    "editorial": "Debate",
    "anioPublicacion": 2014,
    "categoria": "Historia",
    "numeroPaginas": 496,
    "disponible": true,
    "ubicacion": "Estante I-01",
    "descripcion": "Breve historia de la humanidad desde la revolución cognitiva.",
    "fechaRegistro": "2026-03-25T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 52,
    "titulo": "Homo Deus: Breve historia del mañana",
    "autor": "Yuval Noah Harari",
    "isbn": "978-8499926711",
    "editorial": "Debate",
    "anioPublicacion": 2016,
    "categoria": "Historia",
    "numeroPaginas": 496,
    "disponible": false,
    "ubicacion": "Estante I-02",
    "descripcion": "Reflexión sobre el futuro de la especie humana y la biotecnología.",
    "fechaRegistro": "2026-03-25T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 53,
    "titulo": "El gen egoísta",
    "autor": "Richard Dawkins",
    "isbn": "978-8490703816",
    "editorial": "Salvato",
    "anioPublicacion": 1976,
    "categoria": "Divulgación Científica",
    "numeroPaginas": 464,
    "disponible": true,
    "ubicacion": "Estante J-01",
    "descripcion": "Perspectiva de la evolución centrada en los genes.",
    "fechaRegistro": "2026-03-26T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 54,
    "titulo": "Cosmos",
    "autor": "Carl Sagan",
    "isbn": "978-8408053040",
    "editorial": "Planeta",
    "anioPublicacion": 1980,
    "categoria": "Divulgación Científica",
    "numeroPaginas": 384,
    "disponible": true,
    "ubicacion": "Estante J-02",
    "descripcion": "Un viaje fascinante a través de la ciencia, el universo y el hombre.",
    "fechaRegistro": "2026-03-26T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 55,
    "titulo": "Breve historia del tiempo",
    "autor": "Stephen Hawking",
    "isbn": "978-8498927948",
    "editorial": "Crítica",
    "anioPublicacion": 1988,
    "categoria": "Divulgación Científica",
    "numeroPaginas": 256,
    "disponible": true,
    "ubicacion": "Estante J-03",
    "descripcion": "Explicación clara de la cosmología moderna y los agujeros negros.",
    "fechaRegistro": "2026-03-27T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 56,
    "titulo": "Pensar rápido, pensar despacio",
    "autor": "Daniel Kahneman",
    "isbn": "978-8499922072",
    "editorial": "Debate",
    "anioPublicacion": 2011,
    "categoria": "Psicología",
    "numeroPaginas": 672,
    "disponible": false,
    "ubicacion": "Estante K-01",
    "descripcion": "Análisis del pensamiento intuitivo y racional en la toma de decisiones.",
    "fechaRegistro": "2026-03-27T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 57,
    "titulo": "El hombre en busca de sentido",
    "autor": "Viktor E. Frankl",
    "isbn": "978-8425432026",
    "editorial": "Herder",
    "anioPublicacion": 1946,
    "categoria": "Psicología",
    "numeroPaginas": 160,
    "disponible": true,
    "ubicacion": "Estante K-02",
    "descripcion": "Experiencia personal en campos de concentración y desarrollo de la logoterapia.",
    "fechaRegistro": "2026-03-28T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 58,
    "titulo": "Hábitos Atómicos",
    "autor": "James Clear",
    "isbn": "978-6077478027",
    "editorial": "Paidos",
    "anioPublicacion": 2018,
    "categoria": "Desarrollo Personal",
    "numeroPaginas": 328,
    "disponible": true,
    "ubicacion": "Estante K-03",
    "descripcion": "Métodos prácticos para desarrollar hábitos positivos y eliminar los negativos.",
    "fechaRegistro": "2026-03-28T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 59,
    "titulo": "Padre Rico, Padre Pobre",
    "autor": "Robert T. Kiyosaki",
    "isbn": "978-6073118330",
    "editorial": "Aguilar",
    "anioPublicacion": 1997,
    "categoria": "Finanzas Personales",
    "numeroPaginas": 336,
    "disponible": true,
    "ubicacion": "Estante L-01",
    "descripcion": "Lecciones sobre educación financiera, activos y pasivos.",
    "fechaRegistro": "2026-03-29T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 60,
    "titulo": "El inversor inteligente",
    "autor": "Benjamin Graham",
    "isbn": "978-8423425174",
    "editorial": "Deusto",
    "anioPublicacion": 1949,
    "categoria": "Finanzas",
    "numeroPaginas": 624,
    "disponible": false,
    "ubicacion": "Estante L-02",
    "descripcion": "Manual sobre la inversión en valor (Value Investing).",
    "fechaRegistro": "2026-03-29T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 61,
    "titulo": "La riqueza de las naciones",
    "autor": "Adam Smith",
    "isbn": "978-8420635965",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1776,
    "categoria": "Economía",
    "numeroPaginas": 816,
    "disponible": true,
    "ubicacion": "Estante L-03",
    "descripcion": "Obra fundacional del pensamiento económico moderno y libre mercado.",
    "fechaRegistro": "2026-03-30T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 62,
    "titulo": "El Capital: Crítica de la economía política",
    "autor": "Karl Marx",
    "isbn": "978-8437608822",
    "editorial": "Fondo de Cultura Económica",
    "anioPublicacion": 1867,
    "categoria": "Economía",
    "numeroPaginas": 1100,
    "disponible": true,
    "ubicacion": "Estante L-04",
    "descripcion": "Análisis crítico de la producción y estructura del sistema capitalista.",
    "fechaRegistro": "2026-03-30T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 63,
    "titulo": "El arte de la guerra",
    "autor": "Sun Tzu",
    "isbn": "978-8441400191",
    "editorial": "Edaf",
    "anioPublicacion": -500,
    "categoria": "Estrategia",
    "numeroPaginas": 160,
    "disponible": true,
    "ubicacion": "Estante M-01",
    "descripcion": "Tratado militar chino con principios aplicables a la gestión y resolución de conflictos.",
    "fechaRegistro": "2026-03-31T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 64,
    "titulo": "El Príncipe",
    "autor": "Nicolás Maquiavelo",
    "isbn": "978-8420668612",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1532,
    "categoria": "Política",
    "numeroPaginas": 176,
    "disponible": true,
    "ubicacion": "Estante M-02",
    "descripcion": "Tratado político sobre la conservación y ejercicio del poder público.",
    "fechaRegistro": "2026-03-31T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 65,
    "titulo": "La Odisea",
    "autor": "Homero",
    "isbn": "978-8424925000",
    "editorial": "Gredos",
    "anioPublicacion": -800,
    "categoria": "Literatura Clásica",
    "numeroPaginas": 480,
    "disponible": false,
    "ubicacion": "Estante C-16",
    "descripcion": "Poema épico griego sobre el viaje de regreso de Ulises a Ítaca.",
    "fechaRegistro": "2026-04-01T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 66,
    "titulo": "La Ilíada",
    "autor": "Homero",
    "isbn": "978-8424924997",
    "editorial": "Gredos",
    "anioPublicacion": -750,
    "categoria": "Literatura Clásica",
    "numeroPaginas": 520,
    "disponible": true,
    "ubicacion": "Estante C-17",
    "descripcion": "Poema épico que relata la cólera de Aquiles durante la guerra de Troya.",
    "fechaRegistro": "2026-04-01T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 67,
    "titulo": "Hamlet",
    "autor": "William Shakespeare",
    "isbn": "978-8437600888",
    "editorial": "Cátedra",
    "anioPublicacion": 1603,
    "categoria": "Teatro",
    "numeroPaginas": 224,
    "disponible": true,
    "ubicacion": "Estante C-18",
    "descripcion": "Tragedia sobre la duda, la venganza y la locura en la corte danesa.",
    "fechaRegistro": "2026-04-02T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 68,
    "titulo": "Romeo y Julieta",
    "autor": "William Shakespeare",
    "isbn": "978-8437600895",
    "editorial": "Cátedra",
    "anioPublicacion": 1597,
    "categoria": "Teatro",
    "numeroPaginas": 192,
    "disponible": true,
    "ubicacion": "Estante C-19",
    "descripcion": "Clásica tragedia de los dos enamorados de familias enemistadas en Verona.",
    "fechaRegistro": "2026-04-02T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 69,
    "titulo": "Crimen y castigo",
    "autor": "Fiódor Dostoyevski",
    "isbn": "978-8420683004",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1866,
    "categoria": "Literatura",
    "numeroPaginas": 672,
    "disponible": false,
    "ubicacion": "Estante C-20",
    "descripcion": "Exploración de la culpa, la moralidad y la redención de Raskólnikov.",
    "fechaRegistro": "2026-04-03T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 70,
    "titulo": "Los hermanos Karamázov",
    "autor": "Fiódor Dostoyevski",
    "isbn": "978-8420683011",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1880,
    "categoria": "Literatura",
    "numeroPaginas": 1120,
    "disponible": true,
    "ubicacion": "Estante C-21",
    "descripcion": "Novela filosófica sobre el libre albedrío, la fe y la familia.",
    "fechaRegistro": "2026-04-03T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 71,
    "titulo": "Guerra y paz",
    "autor": "León Tolstói",
    "isbn": "978-8497593533",
    "editorial": "Debolsillo",
    "anioPublicacion": 1869,
    "categoria": "Literatura",
    "numeroPaginas": 1280,
    "disponible": true,
    "ubicacion": "Estante C-22",
    "descripcion": "Retrato monumental de la sociedad rusa durante las invasiones napoleónicas.",
    "fechaRegistro": "2026-04-04T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 72,
    "titulo": "Anna Karénina",
    "autor": "León Tolstói",
    "isbn": "978-8420682892",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1878,
    "categoria": "Literatura",
    "numeroPaginas": 1008,
    "disponible": true,
    "ubicacion": "Estante C-23",
    "descripcion": "Tragedia romántica que cuestiona las convenciones sociales de la época.",
    "fechaRegistro": "2026-04-04T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 73,
    "titulo": "La metamorfosis",
    "autor": "Franz Kafka",
    "isbn": "978-8420651362",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1915,
    "categoria": "Literatura",
    "numeroPaginas": 128,
    "disponible": true,
    "ubicacion": "Estante C-24",
    "descripcion": "La historia de Gregorio Samsa y su repentina transformación en insecto.",
    "fechaRegistro": "2026-04-05T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 74,
    "titulo": "El proceso",
    "autor": "Franz Kafka",
    "isbn": "978-8420651379",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1925,
    "categoria": "Literatura",
    "numeroPaginas": 304,
    "disponible": false,
    "ubicacion": "Estante C-25",
    "descripcion": "Josef K. es arrestado sin saber nunca la razón ni los cargos en su contra.",
    "fechaRegistro": "2026-04-05T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 75,
    "titulo": "Ulises",
    "autor": "James Joyce",
    "isbn": "978-8420669381",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1922,
    "categoria": "Literatura Modernista",
    "numeroPaginas": 900,
    "disponible": true,
    "ubicacion": "Estante C-26",
    "descripcion": "Obra cumbre de la narrativa moderna que relata un día en la vida de Leopold Bloom.",
    "fechaRegistro": "2026-04-06T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 76,
    "titulo": "El gran Gatsby",
    "autor": "F. Scott Fitzgerald",
    "isbn": "978-8497593205",
    "editorial": "Debolsillo",
    "anioPublicacion": 1925,
    "categoria": "Literatura",
    "numeroPaginas": 208,
    "disponible": true,
    "ubicacion": "Estante C-27",
    "descripcion": "Crítica a la opulencia y el sueño americano en la década de 1920.",
    "fechaRegistro": "2026-04-06T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 77,
    "titulo": "El viejo y el mar",
    "autor": "Ernest Hemingway",
    "isbn": "978-8497598828",
    "editorial": "Debolsillo",
    "anioPublicacion": 1952,
    "categoria": "Literatura",
    "numeroPaginas": 128,
    "disponible": true,
    "ubicacion": "Estante C-28",
    "descripcion": "Historia de la perseverancia de un anciano pescador cubano.",
    "fechaRegistro": "2026-04-07T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 78,
    "titulo": "Por quién doblan las campanas",
    "autor": "Ernest Hemingway",
    "isbn": "978-8497598811",
    "editorial": "Debolsillo",
    "anioPublicacion": 1940,
    "categoria": "Literatura",
    "numeroPaginas": 528,
    "disponible": false,
    "ubicacion": "Estante C-29",
    "descripcion": "Novela ambientada en la Guerra Civil Española.",
    "fechaRegistro": "2026-04-07T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 79,
    "titulo": "Orgullo y prejuicio",
    "autor": "Jane Austen",
    "isbn": "978-8497593151",
    "editorial": "Debolsillo",
    "anioPublicacion": 1813,
    "categoria": "Literatura",
    "numeroPaginas": 448,
    "disponible": true,
    "ubicacion": "Estante C-30",
    "descripcion": "Sátira social sobre el matrimonio y la moral en la Inglaterra del siglo XIX.",
    "fechaRegistro": "2026-04-08T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 80,
    "titulo": "Cumbres Borrascosas",
    "autor": "Emily Brontë",
    "isbn": "978-8497593168",
    "editorial": "Debolsillo",
    "anioPublicacion": 1847,
    "categoria": "Literatura Gótica",
    "numeroPaginas": 416,
    "disponible": true,
    "ubicacion": "Estante C-31",
    "descripcion": "Intensa novela de pasión, venganza y obsesión en los páramos ingleses.",
    "fechaRegistro": "2026-04-08T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 81,
    "titulo": "Jane Eyre",
    "autor": "Charlotte Brontë",
    "isbn": "978-8497593175",
    "editorial": "Debolsillo",
    "anioPublicacion": 1847,
    "categoria": "Literatura Gótica",
    "numeroPaginas": 592,
    "disponible": true,
    "ubicacion": "Estante C-32",
    "descripcion": "Historia de superación, independencia y crecimiento interior.",
    "fechaRegistro": "2026-04-09T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 82,
    "titulo": "Frankenstein",
    "autor": "Mary Shelley",
    "isbn": "978-8497593182",
    "editorial": "Debolsillo",
    "anioPublicacion": 1818,
    "categoria": "Literatura Gótica / Ciencia Ficción",
    "numeroPaginas": 288,
    "disponible": false,
    "ubicacion": "Estante C-33",
    "descripcion": "Reflexión pionera sobre la creación, la ciencia y la responsabilidad ética.",
    "fechaRegistro": "2026-04-09T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 83,
    "titulo": "Drácula",
    "autor": "Bram Stoker",
    "isbn": "978-8497593199",
    "editorial": "Debolsillo",
    "anioPublicacion": 1897,
    "categoria": "Literatura Gótica",
    "numeroPaginas": 512,
    "disponible": true,
    "ubicacion": "Estante C-34",
    "descripcion": "La célebre novela epistolar que dio origen a la figura moderna del vampiro.",
    "fechaRegistro": "2026-04-10T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 84,
    "titulo": "El retrato de Dorian Gray",
    "autor": "Oscar Wilde",
    "isbn": "978-8497593212",
    "editorial": "Debolsillo",
    "anioPublicacion": 1890,
    "categoria": "Literatura",
    "numeroPaginas": 256,
    "disponible": true,
    "ubicacion": "Estante C-35",
    "descripcion": "Exploración del hedonismo, la vanidad y la corrupción moral.",
    "fechaRegistro": "2026-04-10T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 85,
    "titulo": "Los miserables",
    "autor": "Victor Hugo",
    "isbn": "978-8420682885",
    "editorial": "Alianza Editorial",
    "anioPublicacion": 1862,
    "categoria": "Literatura",
    "numeroPaginas": 1344,
    "disponible": true,
    "ubicacion": "Estante C-36",
    "descripcion": "Épica francesa sobre la justicia social, el perdón y la redención.",
    "fechaRegistro": "2026-04-11T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 86,
    "titulo": "El del fin del mundo y antes del amanecer",
    "autor": "Haruki Murakami",
    "isbn": "978-8483103135",
    "editorial": "Tusquets",
    "anioPublicacion": 1985,
    "categoria": "Literatura Contemporánea",
    "numeroPaginas": 480,
    "disponible": false,
    "ubicacion": "Estante C-37",
    "descripcion": "Dos historias paralelas sobre la identidad, la mente y el aislamiento.",
    "fechaRegistro": "2026-04-11T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 87,
    "titulo": "Tokio blues (Norwegian Wood)",
    "autor": "Haruki Murakami",
    "isbn": "978-8483103128",
    "editorial": "Tusquets",
    "anioPublicacion": 1987,
    "categoria": "Literatura Contemporánea",
    "numeroPaginas": 384,
    "disponible": true,
    "ubicacion": "Estante C-38",
    "descripcion": "Nostálgica novela sobre el duelo, el amor y la juventud en el Tokio de los años 60.",
    "fechaRegistro": "2026-04-12T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 88,
    "titulo": "1Q84",
    "autor": "Haruki Murakami",
    "isbn": "978-8483103111",
    "editorial": "Tusquets",
    "anioPublicacion": 2009,
    "categoria": "Literatura Contemporánea",
    "numeroPaginas": 944,
    "disponible": true,
    "ubicacion": "Estante C-39",
    "descripcion": "Mundo distópico y surrealista entrelazado por el destino de dos personajes.",
    "fechaRegistro": "2026-04-12T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 89,
    "titulo": "El nombre de la rosa",
    "autor": "Umberto Eco",
    "isbn": "978-8426418227",
    "editorial": "Lumen",
    "anioPublicacion": 1980,
    "categoria": "Novela Histórica",
    "numeroPaginas": 640,
    "disponible": true,
    "ubicacion": "Estante C-40",
    "descripcion": "Misterio detectivesco en una abadía benedictina del siglo XIV.",
    "fechaRegistro": "2026-04-13T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 90,
    "titulo": "El péndulo de Foucault",
    "autor": "Umberto Eco",
    "isbn": "978-8426418234",
    "editorial": "Lumen",
    "anioPublicacion": 1988,
    "categoria": "Novela Histórica",
    "numeroPaginas": 800,
    "disponible": false,
    "ubicacion": "Estante C-41",
    "descripcion": "Sátira erudita sobre teorías conspirativas y redes herméticas.",
    "fechaRegistro": "2026-04-13T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 91,
    "titulo": "La sombra del viento",
    "autor": "Carlos Ruiz Zafón",
    "isbn": "978-8408043645",
    "editorial": "Planeta",
    "anioPublicacion": 2001,
    "categoria": "Literatura Contemporánea",
    "numeroPaginas": 576,
    "disponible": true,
    "ubicacion": "Estante C-42",
    "descripcion": "Primer libro del Cementerio de los Libros Olvidados ambientado en Barcelona.",
    "fechaRegistro": "2026-04-14T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 92,
    "titulo": "El juego del ángel",
    "autor": "Carlos Ruiz Zafón",
    "isbn": "978-8408081180",
    "editorial": "Planeta",
    "anioPublicacion": 2008,
    "categoria": "Literatura Contemporánea",
    "numeroPaginas": 672,
    "disponible": true,
    "ubicacion": "Estante C-43",
    "descripcion": "Aventura gótica de intriga, amor y tragedia en la Barcelona de los años 20.",
    "fechaRegistro": "2026-04-14T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 93,
    "titulo": "Inteligencia Emocional",
    "autor": "Daniel Goleman",
    "isbn": "978-8449308581",
    "editorial": "Kairós",
    "anioPublicacion": 1995,
    "categoria": "Psicología",
    "numeroPaginas": 528,
    "disponible": true,
    "ubicacion": "Estante K-04",
    "descripcion": "Cómo las habilidades emocionales influyen más que el coeficiente intelectual.",
    "fechaRegistro": "2026-04-15T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 94,
    "titulo": "Los 7 hábitos de la gente altamente efectiva",
    "autor": "Stephen R. Covey",
    "isbn": "978-8449331893",
    "editorial": "Paidos",
    "anioPublicacion": 1989,
    "categoria": "Liderazgo",
    "numeroPaginas": 464,
    "disponible": false,
    "ubicacion": "Estante M-03",
    "descripcion": "Principios para la efectividad personal, profesional e interpersonal.",
    "fechaRegistro": "2026-04-15T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 95,
    "titulo": "Empieza con el porqué",
    "autor": "Simon Sinek",
    "isbn": "978-8416029082",
    "editorial": "Empresa Activa",
    "anioPublicacion": 2009,
    "categoria": "Liderazgo",
    "numeroPaginas": 256,
    "disponible": true,
    "ubicacion": "Estante M-04",
    "descripcion": "Cómo grandes líderes inspiran a la acción con el círculo dorado.",
    "fechaRegistro": "2026-04-16T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 96,
    "titulo": "The Lean Startup",
    "autor": "Eric Ries",
    "isbn": "978-0307887894",
    "editorial": "Crown Business",
    "anioPublicacion": 2011,
    "categoria": "Emprendimiento",
    "numeroPaginas": 336,
    "disponible": true,
    "ubicacion": "Estante M-05",
    "descripcion": "Creación de empresas viables mediante experimentación continua e innovación.",
    "fechaRegistro": "2026-04-16T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 97,
    "titulo": "Zero to One",
    "autor": "Peter Thiel, Blake Masters",
    "isbn": "978-0804139298",
    "editorial": "Crown Business",
    "anioPublicacion": 2014,
    "categoria": "Emprendimiento",
    "numeroPaginas": 224,
    "disponible": true,
    "ubicacion": "Estante M-06",
    "descripcion": "Cómo construir empresas innovadoras que creen cosas completamente nuevas.",
    "fechaRegistro": "2026-04-17T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 98,
    "titulo": "Scrum: The Art of Doing Twice the Work in Half the Time",
    "autor": "Jeff Sutherland",
    "isbn": "978-0385346450",
    "editorial": "Currency",
    "anioPublicacion": 2014,
    "categoria": "Gestión de Proyectos",
    "numeroPaginas": 256,
    "disponible": false,
    "ubicacion": "Estante G-06",
    "descripcion": "Guía práctica del creador del marco de trabajo ágil Scrum.",
    "fechaRegistro": "2026-04-17T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 99,
    "titulo": "User Story Mapping",
    "autor": "Jeff Patton",
    "isbn": "978-1491904909",
    "editorial": "O'Reilly Media",
    "anioPublicacion": 2014,
    "categoria": "Gestión de Productos",
    "numeroPaginas": 324,
    "disponible": true,
    "ubicacion": "Estante G-07",
    "descripcion": "Técnica para construir productos de software centrados en las historias de usuario.",
    "fechaRegistro": "2026-04-18T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 100,
    "titulo": "Continuous Delivery",
    "autor": "Jez Humble, David Farley",
    "isbn": "978-0321601910",
    "editorial": "Addison-Wesley",
    "anioPublicacion": 2010,
    "categoria": "DevOps",
    "numeroPaginas": 512,
    "disponible": true,
    "ubicacion": "Estante G-08",
    "descripcion": "Automatización de pruebas y despliegues para ciclos de entrega rápidos y confiables.",
    "fechaRegistro": "2026-04-18T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 101,
    "titulo": "Computer Architecture: A Quantitative Approach",
    "autor": "John L. Hennessy, David A. Patterson",
    "isbn": "978-0128119051",
    "editorial": "Morgan Kaufmann",
    "anioPublicacion": 2017,
    "categoria": "Hardware / Arquitectura",
    "numeroPaginas": 856,
    "disponible": true,
    "ubicacion": "Estante D-05",
    "descripcion": "Principios cuantitativos de diseño y rendimiento de procesadores modernos.",
    "fechaRegistro": "2026-04-19T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 102,
    "titulo": "Structure and Interpretation of Computer Programs (SICP)",
    "autor": "Harold Abelson, Gerald Jay Sussman",
    "isbn": "978-0262510875",
    "editorial": "MIT Press",
    "anioPublicacion": 1996,
    "categoria": "Ciencias de la Computación",
    "numeroPaginas": 657,
    "disponible": true,
    "ubicacion": "Estante A-07",
    "descripcion": "Texto clásico sobre la abstracción y control de la complejidad en programación.",
    "fechaRegistro": "2026-04-19T00:00:00.000Z",
    "fechaModificacion": null
  },
  {
    "id": 103,
    "titulo": "Code: The Hidden Language of Computer Hardware and Software",
    "autor": "Charles Petzold",
    "isbn": "978-0735611313",
    "editorial": "Microsoft Press",
    "anioPublicacion": 2000,
    "categoria": "Divulgación Tecnológica",
    "numeroPaginas": 400,
    "disponible": true,
    "ubicacion": "Estante D-06",
    "descripcion": "Explicación accesible sobre cómo se construyen las computadoras desde el código Morse hasta los procesadores.",
    "fechaRegistro": "2026-04-20T00:00:00.000Z",
    "fechaModificacion": null
  }
];

module.exports = books;